### ISSUE TITLE
How to get text of chapter by it's id?

### ISSUE THREAD

**Issue by kevan18081990** [witekbobrowski/EPUBKit#3]

**Comment by witekbobrowski** [comment]
Hi! So sorry for such a late response :( Thank you for showing interest in the library though!

If you are still interested in the answer here it is.

Current version of the library does not let you access the chapters text, since a chapter is basically a static web-page or to be more precise, an HTML file. So parsing the contents is not something I have implemented already.

But getting to the file itself is pretty easy. What you need is a `EPUBManifestItem` object, that has the `path` property. There are actually two types of ids for a chapter. First id is relative to the `EPUBSpineItem` (which is an item of spine, a table of contents basically). And the second one is of the `EPUBManifestItem ` mentioned above. 
So if your id is the id od spine item then:
```swift
let document: EPUBDocument = XXX
let spineItemId = XXX
let spineItem = document.spine.items.first { $0.id == spineItemId }
let path = document.manifest.items[spineItem!.idref]?.path
```
Else, if the id you have is the id of manifest item simply access it as I did in the last line
